volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shopping-cart
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 55000:5432
    volumes:
      - data:/var/lib/postgresql